---
title: "566 Assignment 1"
author: "Matthew Stoebe"
date: "`r Sys.Date()`"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Load necessary library
library(ggplot2)


# Create the plot
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(aes(color = factor(cyl))) +  # Scatter plot colored by number of cylinders
  geom_smooth(method = "loess", se = TRUE, color = "black", size = 1) +  # Curvy line with confidence interval for all data
  geom_smooth(aes(color = factor(cyl)), method = "lm", se = FALSE, linetype = "dashed") +  # Straight lines fit to each group
  geom_smooth(method = "loess", se = FALSE, color = "black", linetype = "solid", size = 1) +  # Curvy line for all data (without CI)
  scale_color_manual(values = c("4" = "red", "6" = "green", "8" = "blue")) +  # Set colors for cylinders
  labs(title = "Exploration of MPG Dataset", 
       x = "Displacement (liters)", 
       y = "Highway mileage",
       color = "Number of cylinders") +
  theme_minimal() +
  theme(
    panel.background = element_rect(fill = "grey85", color = NA),  
    plot.background = element_rect(fill = "grey85", color = NA),   
    panel.grid.major = element_line(color = "white"),  
    panel.grid.minor = element_line(color = "white"),
    axis.ticks = element_blank(),  
    axis.text = element_text(color = "black", face = "bold")  
  )


```

```{r}
# Create the plot
ggplot(mpg, aes(x = factor(cyl), fill = factor(cyl))) +
  geom_bar() +  # Bar plot
  facet_wrap(~ drv) +  # Facet by drive type
  labs(title = "Exploration of MPG Dataset", 
       subtitle = "Comparison across drive types",
       x = "Number of cylinders", 
       y = "Number of cars",
       fill = "Number of cylinders") +
  scale_fill_manual(values = c("4" = "red", "6" = "cyan", "8" = "purple")) +  # Set colors
  theme_minimal() +
  theme(
    panel.background = element_rect(fill = "grey85", color = NA),  
    plot.background = element_rect(fill = "grey85", color = NA),   
    strip.background = element_rect(fill = "grey85", color = NA),  
    panel.grid.major = element_line(color = "white"),  
    panel.grid.minor = element_line(color = "white"),
    axis.ticks = element_blank(),  
    axis.text = element_text(color = "black", face = "bold")
  )



```



