---
title: "566_Assignment_3"
author: "Matthew Stoebe"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(socviz)
library(ggplot2)
library(dplyr)
library(scales) # for muted colors
```


```{r, fig.width=12, fig.height=8}
# Load the county_map and county_data datasets
data("county_map")
data("county_data")


county_data$winning_margin <- 100 * county_data$diff_2016 / county_data$total_votes_2016

county_combined <- inner_join(county_map, county_data, by = "id")


ggplot(county_combined, aes(x = long, y = lat, group = group, fill = winning_margin)) +
  geom_polygon(color = "grey", size = 0.01) + 
  coord_fixed(1) + 
  scale_fill_gradient2(low = "blue", mid = muted("purple"), high = "red", midpoint = 0, 
                       na.value = "gray50", limits = c(-100, 100), 
                       name = "Percent") +
  theme_minimal() +
  labs(title = "County-Level Winning Margins in the 2016 Election") +
  theme(axis.text = element_blank(), 
        axis.title = element_blank(),
        panel.grid = element_blank(),
        plot.title = element_text(hjust = 0.5))

```



