---
title: "HW4"
author: "Matthew Stoebe"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Install necessary packages if not already installed
install.packages(c("forecast", "ggplot2"))

# Load the packages
library(forecast)
library(ggplot2)

```

```{r}
set.seed(123)

n <- 100
phi <- 0.6   
theta <- 0.9 

arma11_series <- arima.sim(n = n, list(ar = phi, ma = theta), sd = 1)
arma10_series <- arima.sim(n = n, list(ar = phi), sd = 1)
arma01_series <- arima.sim(n = n, list(ma = theta), sd = 1)

# Plot the time series
ts.plot(arma11_series, main = "ARMA(1,1) Time Series", ylab = "Value")
ts.plot(arma10_series, main = "AR(1) Time Series", ylab = "Value")
ts.plot(arma01_series, main = "MA(1) Time Series", ylab = "Value")

acf_arma11 <- acf(arma11_series, plot = FALSE)
acf_arma10 <- acf(arma10_series, plot = FALSE)
acf_arma01 <- acf(arma01_series, plot = FALSE)

pacf_arma11 <- pacf(arma11_series, plot = FALSE)
pacf_arma10 <- pacf(arma10_series, plot = FALSE)
pacf_arma01 <- pacf(arma01_series, plot = FALSE)

theoretical_acf_arma11 <- ARMAacf(ar = phi, ma = theta, lag.max = 20)
theoretical_acf_arma10 <- ARMAacf(ar = phi, lag.max = 20)
theoretical_acf_arma01 <- ARMAacf(ma = theta, lag.max = 20)

plot(acf_arma11, main = "Sample ACF vs Theoretical ACF for ARMA(1,1)")
lines(0:20, theoretical_acf_arma11, col = "red", lty = 2)
legend("topright", legend = c("Sample ACF", "Theoretical ACF"), col = c("black", "red"), lty = c(1, 2))

plot(acf_arma10, main = "Sample ACF vs Theoretical ACF for AR(1)")
lines(0:20, theoretical_acf_arma10, col = "red", lty = 2)
legend("topright", legend = c("Sample ACF", "Theoretical ACF"), col = c("black", "red"), lty = c(1, 2))

plot(acf_arma01, main = "Sample ACF vs Theoretical ACF for MA(1)")
lines(0:20, theoretical_acf_arma01, col = "red", lty = 2)
legend("topright", legend = c("Sample ACF", "Theoretical ACF"), col = c("black", "red"), lty = c(1, 2))


plot(pacf_arma11, main = "Sample PACF for ARMA(1,1)", 
     ylim = c(min(pacf_arma11$acf), max(pacf_arma11$acf)))
abline(h = 0, col = "black")

plot(pacf_arma10, main = "Sample PACF vs Theoretical PACF for AR(1)", 
     ylim = c(min(pacf_arma10$acf), max(pacf_arma10$acf)))
abline(h = 0, col = "black")


plot(pacf_arma01, main = "Sample PACF vs Theoretical PACF for MA(1)", 
     ylim = c(min(pacf_arma01$acf), max(pacf_arma01$acf)))
abline(h = 0, col = "black")


```

These results align with what is expected from table 3.1 in the textbook


