---
title: "HW6_567"
author: "Matthew Stoebe"
date: "`r Sys.Date()`"
output: html_document
---


```{r}

x <- seq(-10, 10, length.out = 1000)


cauchy_density <- dcauchy(x, location = 0, scale = 1)
normal_density <- dnorm(x, mean = 0, sd = 1)


plot(x, cauchy_density, type = "l", col = "red", lwd = 2,
     ylab = "Density", main = "Standard Cauchy and Normal Densities",
     xlab = "x")
lines(x, normal_density, col = "blue", lwd = 2)
legend("topright", legend = c("Cauchy", "Normal"),
       col = c("red", "blue"), lwd = 2)


```

```{r}

set.seed(111)
n <- 100000

u <- runif(n, min = 0, max = 1)
x_cauchy <- tan(pi * (u - 0.5))

hist(x_cauchy, breaks = 10000, main = "Histogram of Standard Cauchy Sample (Inverse Transform)",
     xlab = "x", col = "lightblue", border = "grey")


```

```{r}
# Problem 1(d)

# Set a different seed
set.seed(456)

# Generate another sample
u2 <- runif(n, min = 0, max = 1)
x_cauchy2 <- tan(pi * (u2 - 0.5))

# Plot histogram
hist(x_cauchy2, breaks = 100, main = "Histogram of Second Standard Cauchy Sample",
     xlab = "x", col = "lightgreen", border = "grey")

```

```{r}
# Problem 1(e)

# Set seed for reproducibility
set.seed(789)

# Generate standard normal random variables
n <- 10000
Z1 <- rnorm(n, mean = 0, sd = 1)
Z2 <- rnorm(n, mean = 0, sd = 1)

# Compute the ratio
x_cauchy_ratio <- Z1 / Z2

# Plot histogram
hist(x_cauchy_ratio, breaks = 100, main = "Histogram of Standard Cauchy Sample (Ratio Method)",
     xlab = "x", col = "pink", border = "grey")

```

